name: workflow demo

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install Package
        run: pip install pytest
        
      - name: Run tests
        run: pytest testWallet.py